use_frameworks!

target 'LTAutoScrollView_Example' do
    
    pod 'Kingfisher', '~> 4.7.0'
  pod 'LTAutoScrollView', :path => '../'

#  target 'LTAutoScrollView_Tests' do
#    inherit! :search_paths
#
#
#  end
end
